
services:

  mysql:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d/
    command: ["mysqld", "--mysql-native-password=ON"]
    networks:
      - my_network

  flask-app:
    build:
      context: ./flask-app  # Asegúrate de que este directorio contenga tu Dockerfile
    container_name: myapp
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DB=mydatabase
    volumes:
      - ./flask-app/src:/app
    networks:
      - my_network
  
  
  
    # kali:
  #   build: ./kali
  #   container_name: kali_container
  #   tty: true
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - /kali/xrdp:/etc/xrdp
  #   ports:
  #     - "3389:3389"
  #   environment:
  #     DISPLAY: :0
  #   # command: /bin/bash -c "apt update && apt install -y xrdp && systemctl start xrdp && tail -f /var/log/xrdp.log"
  #   networks:
  #     - my_network




volumes:
  # mysql-data:
  flask-app:


networks:
  my_network:
    driver: bridge


  # kali-vnc:
  #   build: ./kali
  #   ports:
  #     - "5901:5901"
  #   volumes:
  #     - ./data:/home/vncuser/data
  #   environment:
  #     DISPLAY: ":1"
  #     VNC_PASSWORD: "your_password"
  #   networks:
  #     - my_network





  # kali:
  #   image: kalilinux/kali-linux-docker
  #   container_name: kali
  #   ports:
  #     - "4444:4444"  # Puerto para herramientas de pruebas (ajustar según sea necesario)
  #   stdin_open: true
  #   tty: true

